fluxionPj/firstapp/urls.py
from django.conf.urls import url
from firstapp.views import MemoList,MemoDetail

urlpatterns = [
    url(r'^$',MemoList.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', MemoDetail.as_view(), name='detail'),
]

fluxionPj/fluxionPj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    # memo 문자열로 시작하는 url 요청이 오면 memo.urls 파일에 있는 url 로 매핑
    url('memo/', include(('firstapp.urls', 'memo'), namespace='memo')),
]

fluxionPj/firstapp/models.py
from django.db import models

# Create your models here.
class Memo(models.Model):
    content = models.CharField(max_length=1000, blank=True, null=True)

fluxionPj/firstapp/views.py
from django.views.generic import ListView, DetailView
from firstapp.models import Memo

# Create your views here.
class MemoList(ListView) :
    model = Memo

class MemoDetail(DetailView) :
    model = Memo

fluxionPj/firstapp/templates/firstapp/memo_detail.html
<!DOCTYPE html>
<html>
<head>
    <title> Memo </title>
</head>
<body>
    <div id="content">
        <h1>메모장 상세</h1>
            {{ object.content }} 
    </div>
</body>
</html>

fluxionPj/firstapp/templates/firstapp/memo_list.html
<!DOCTYPE html>
<html>
<head>
    <title> Memo </title>
</head>
<body>
    <div id="content">
        <h1>메모장</h1>
        <ul>
            {% for memo in object_list %}
                <li><a href="{% url 'memo:detail' memo.id %}"> {{ memo }} </a></li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>